forms.py
# -*- coding:utf-8 -*-
_author_ = 'weijian'

import wtforms
from wtforms.validators import length,email

class LoginForm(wtforms.Form):
    email = wtforms.StringField(validators=[length(min=5,max=20),email()]) #validators位验证器，验证长度length，验证邮箱格式email
    password = wtforms.StringField(validators=[length(min=6,max=20)])

app.py
from flask import Flask
import config
from exts import db,mail
from blueprints import qa_bp #已经先存放在了init文件中
from blueprints import user_bp #引用蓝图中的模块
from blueprints import other_bp


app = Flask(__name__)
app.config.from_object(config)
db.init_app(app)
mail.init_app(app) #将APP继承到mail中，之后才能发邮件

#使蓝图中的方法生效
app.register_blueprint(qa_bp)
app.register_blueprint(user_bp)
app.register_blueprint(other_bp)




if __name__ == '__main__':
    app.run(host='0.0.0.0',port=5000,debug=True)

blueprints/__init__.py
# -*- coding:utf-8 -*-
_author_ = 'weijian'

#将需要导入的文件同一放init文件
from .qa import bp as qa_bp
from .user import bp as user_bp
from .other import bp as other_bp

blueprints/other.py
# -*- coding:utf-8 -*-
_author_ = 'weijian'

import flask,json

from flask import Blueprint,render_template

#此文件为问答页面的各种操作

bp = Blueprint('other',__name__,url_prefix="/") #/为基础路由，访问问答时需经过这个路由
# 实例化bp，把当前这个python文件当作一个服务，__name__代表当前这个python文件


# 'index'是接口路径，methods不写，默认get请求     
@bp.route('/index',methods=['get'])
# get方式访问
def index():
    ren = {'msg':'成功访问首页','msg_code':200}
    #json.dumps 序列化时对中文默认使用的ascii编码.想输出中文需要指定ensure_ascii=False
    return json.dumps(ren,ensure_ascii=False)

#post入参访问方式一：url格式参数
@bp.route('/article',methods=['post'])
def article():
    #url格式参数?id=12589&name='lishi'
    id = flask.request.args.get('id')

    if id:
        if id == '12589':
            ren = {'msg':'成功访问文章','msg_code':200}
        else:
            ren = {'msg':'找不到文章','msg_code':400}
    else:
        ren = {'msg':'请输入文章id参数','msg_code':-1}
    return json.dumps(ren,ensure_ascii=False)

#post入参访问方式二：from-data（k-v）格式参数
@bp.route('/login',methods=['post'])
def login():
    #from-data格式参数
    usrname = flask.request.values.get('usrname')
    pwd = flask.request.values.get('pwd')

    if usrname and pwd:
        if usrname =='test' and pwd =='123456':
            ren = {'msg':'登录成功','msg_code':200}
        else:
            ren = {'msg':'用户名或密码错误','msg_code':-1}
    else:
        ren = {'msg':'用户名或密码为空','msg_code':1001}
    return json.dumps(ren,ensure_ascii=False)

#post入参访问方式二：josn格式参数  
@bp.route('/loginjosn',methods=['post'])
def loginjosn():
    #from-data格式参数
    usrname = flask.request.json.get('usrname')
    pwd = flask.request.json.get('pwd')

    if usrname and pwd:
        if usrname =='test' and pwd =='123456':
            ren = {'msg':'登录成功','msg_code':200}
        else:
            ren = {'msg':'用户名或密码错误','msg_code':-1}
    else:
        ren = {'msg':'用户名或密码为空','msg_code':1001}
    return json.dumps(ren,ensure_ascii=False)

blueprints/qa.py
# -*- coding:utf-8 -*-
_author_ = 'weijian'

from flask import Blueprint,render_template

#此文件为问答页面的各种操作

bp = Blueprint('qa',__name__,url_prefix="/") #/为基础路由，访问问答时需经过这个路由

@bp.route('/')
def index():
    return render_template('index.html')

blueprints/user.py
# -*- coding:utf-8 -*-
_author_ = 'weijian'


from flask import Blueprint,render_template
from exts import mail
from flask_mail import Message

bp = Blueprint('user',__name__,url_prefix="/user") #/user为基础路由，访问user时需经过这个路由

@bp.route('/login')
def login():
    return render_template('login.html')


@bp.route('/register')
def register():
    return render_template('register.html')

@bp.route('/mail')
def my_mail():
    message = Message(
        subject='邮箱测试',
        recipients=['649514913@qq.com'],
        body='这是测试邮件',
        sender='753563304@qq.com'
    )
    mail.send(message)
    return 'success'

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{url_for('static',filename='bootstrap/bootstrap.4.6.min.css')}}">
    <link rel="stylesheet" href="{{ url_for('static',filename='css/init.css') }}">
    {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container"> <!--加一个div标签class="container，就可以居中显示-->
        <a class="navbar-brand" href="#">知了问答</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">首页<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">发布问答</a>
                </li>
                <li class="nav-item  ml-2"> <!--class="nav-item"靠左显示,ml-2表示左边间隔2像素-->
                    <form class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="search" placeholder="关键字" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav"> <!--将mr-auto删除就可以靠右显示-->
                <li class="nav-item"> <!--将active删除去除高亮显示-->
                    <a class="nav-link" href="{{ url_for('user.login') }}">登录<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container">
    {% block body %}{% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends "base.html" %}   <!--继承base.html中的模板，即导航栏-->

{% block title %}知了问答-首页{% endblock %}


{% block head %}

{% endblock %}


{% block body %}
<h1>首页</h1>
{% endblock %}

templates/login.html
{% extends "base.html" %}   <!--继承base.html中的模板，即导航栏-->

{% block title %}知了问答-登录{% endblock %}


{% block head %}

{% endblock %}


{% block body %}
  <div class="row mt-4">
    <div class='col'></div>
    <div class='col'>
      <form>
        <div class="form-group">
          <label for="exampleInputEmail1">邮箱</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
          <small id="emailHelp" class="form-text text-muted">我们不会将邮箱用于其他用途</small>
        </div>

        <div class="form-group">
          <label for="exampleInputEmail1">验证码</label>

          <div class="input-group">

            <input type="text" class="form-control">

            <div class="input-group-append">
              <button class="btn btn-outline-secondary" type="button">获取验证码</button>
            </div>

          </div>

        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">密码</label>
          <input type="password" class="form-control" id="exampleInputPassword1">
        </div>

        <div class="form-group">
          <label for="exampleInputPassword1">确认密码</label>
          <input type="password" class="form-control" id="exampleInputPassword1">
        </div>

        <button type="submit" class="btn btn-primary btn-block">立即登录</button> <!--btn-block可将该行和其他行宽度一致 -->
      </form>
    </div>
    <div class='col'></div>
  </div>


{% endblock %}

templates/register.html
{% extends "base.html" %}   <!--继承base.html中的模板，即导航栏-->

{% block title %}知了问答-注册{% endblock %}


{% block head %}

{% endblock %}


{% block body %}

{% endblock %}